name: a1_workspace
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  persistent_bottom_nav_bar: ^6.2.1
  dropdown_button2: ^2.3.9
  syncfusion_flutter_calendar: ^28.1.41
  flutter_native_splash: ^2.4.4
  dio: ^5.7.0
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  flutter_datetime_picker_utils: ^1.0.1
  get_it: ^8.0.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  shared_preferences: ^2.5.1
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  loading_animation_widget: ^1.3.0
  custom_refresh_indicator: ^4.0.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  open_file: ^3.5.10
  flutter_pdfview: ^1.4.0

flutter_icons:
  image_path: assets/icon/icon.png
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: sf
      fonts:
        - asset: fonts/SFPRODISPLAYBOLD.OTF
    - family: sf-regular
      fonts:
        - asset: fonts/SFPRODISPLAYREGULAR.OTF
    - family: sf-medium
      fonts:
        - asset: fonts/SFPRODISPLAYMEDIUM.OTF

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/splash.png
